# Generated by Django 3.2.5 on 2022-01-25 11:21

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personlization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_theme', models.CharField(choices=[('YELLOW', 'YELLOW'), ('RED', 'RED'), ('BLUE', 'BLUE'), ('ORANGE', 'ORANGE')], max_length=50, verbose_name='Color Theme for Portfolio Colors')),
            ],
            options={
                'verbose_name': 'User_info',
                'verbose_name_plural': 'User_infos',
            },
        ),
        migrations.CreateModel(
            name='Social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook_url', models.CharField(help_text='field for facebook account link', max_length=50, verbose_name='Facebook link')),
            ],
            options={
                'verbose_name': 'Social_media',
                'verbose_name_plural': 'Social_medias',
            },
        ),
        migrations.CreateModel(
            name='User_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(help_text='Full name to be displayed on portfolio', max_length=50, verbose_name='FullName')),
                ('Country', django_countries.fields.CountryField(max_length=2)),
                ('City', models.CharField(help_text='name of city that would be displayed on front page', max_length=50, verbose_name='City_Name')),
                ('Phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
            ],
            options={
                'verbose_name': 'User_info',
                'verbose_name_plural': 'User_infos',
            },
        ),
    ]
