# Generated by Django 3.2.5 on 2022-01-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social_media_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Facebook_url', models.CharField(help_text='field for facebook account link', max_length=50, verbose_name='Facebook link')),
                ('user_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user_info', verbose_name='')),
            ],
            options={
                'verbose_name': 'Social_media_info',
                'verbose_name_plural': 'Social_medias_info',
            },
        ),
        migrations.DeleteModel(
            name='Social_media',
        ),
    ]
