# Generated by Django 3.2.5 on 2022-01-25 11:52

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20220125_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personlization',
            options={'verbose_name': 'Personalization', 'verbose_name_plural': 'Personalization'},
        ),
        migrations.AlterModelOptions(
            name='user_info',
            options={'verbose_name': 'User_Information', 'verbose_name_plural': 'User_Information'},
        ),
        migrations.AddField(
            model_name='personlization',
            name='User_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.user_info', verbose_name='User_info'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Country',
            field=django_countries.fields.CountryField(help_text='Country of Residence', max_length=2),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='Phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Phone number to display on home page', max_length=128, region=None, verbose_name='Phone Number'),
        ),
        migrations.DeleteModel(
            name='Social_media_info',
        ),
    ]
