# Generated by Django 3.2.5 on 2022-01-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20220125_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personlization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.personlization', verbose_name='personalization')),
                ('User_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portfolio.user_info', verbose_name='user_info')),
            ],
        ),
    ]
