# Generated by Django 3.2.5 on 2022-01-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='Personlization',
        ),
        migrations.AlterField(
            model_name='personlization',
            name='User_info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info'),
        ),
    ]
