# Generated by Django 3.2.5 on 2022-01-25 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20220125_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personlization',
            old_name='User_info',
            new_name='Portfolio',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='User_info',
        ),
        migrations.AddField(
            model_name='user_info',
            name='Portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info'),
        ),
    ]
