# Generated by Django 3.2.5 on 2022-01-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_personlization_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='Portfolio_name',
            field=models.CharField(max_length=50, null=True, verbose_name='OPEN SOURCE PORTFOLIO'),
        ),
    ]
