# Generated by Django 3.2.5 on 2022-01-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Portfolio_name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='OPEN SOURCE PORTFOLIO'),
        ),
    ]
