# Generated by Django 3.2.5 on 2022-01-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_personlization_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='Fullname',
            field=models.CharField(default='Full Name', help_text='Full name to be displayed on portfolio', max_length=50, verbose_name='FullName'),
        ),
    ]
