# Generated by Django 3.2.5 on 2022-01-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_social_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_info',
            name='Portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info'),
        ),
    ]
