# Generated by Django 3.2.5 on 2022-01-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_rename_mail_account_name_social_info_email_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_info',
            name='EMail_account_name',
            field=models.URLField(verbose_name='Email Name'),
        ),
    ]
