# Generated by Django 3.2.5 on 2022-01-25 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0024_alter_social_info_email_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlization',
            name='Portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.RESTRICT, to='portfolio.portfolio', verbose_name='User_info'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='EMail_account_name',
            field=models.EmailField(max_length=254, verbose_name='Email Name'),
        ),
    ]
