# Generated by Django 3.2.5 on 2022-01-25 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_alter_personlization_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlization',
            name='Terminal_icon_blink',
            field=models.BooleanField(default=True, null=True, verbose_name='ON or OFF blink terminal icon in homepage'),
        ),
    ]
