# Generated by Django 3.2.5 on 2022-01-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_auto_20220125_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='social_info',
            name='EMail_account_name',
            field=models.EmailField(default='None', max_length=254, verbose_name='Email Name'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='Facebook_url',
            field=models.URLField(default='None', verbose_name='Facebook Account Url'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='Instagram_url',
            field=models.URLField(default='None', verbose_name='Instagram Account Url'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='LinkedIn_url',
            field=models.URLField(default='None', verbose_name='LinkedIn Account Url'),
        ),
        migrations.AlterField(
            model_name='social_info',
            name='Twitter_url',
            field=models.URLField(default='None', verbose_name='Twitter Account Url'),
        ),
    ]
