# Generated by Django 3.2.5 on 2022-01-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0031_auto_20220125_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social_info',
            old_name='EMail_account_name',
            new_name='Email_account_name',
        ),
        migrations.AddField(
            model_name='user_info',
            name='Curriculum_vitae',
            field=models.FileField(help_text='File upload for cv', null=True, upload_to='upload/', verbose_name='Curriculum_Vitae'),
        ),
    ]
