# Generated by Django 3.2.5 on 2022-01-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_auto_20220125_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_info',
            name='profession',
            field=models.CharField(help_text='professions to be placed on homepage. Use comma to separate profession', max_length=100, null=True, verbose_name='Professions'),
        ),
    ]
