# Generated by Django 3.2.5 on 2022-01-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_portfolio_portfolio_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_info',
            name='Github_url',
            field=models.URLField(default='None', verbose_name='Github Account Url'),
        ),
    ]
