# Generated by Django 3.2.5 on 2022-01-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_social_info_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlization',
            name='Background_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Background picture for home page'),
        ),
    ]
