# Generated by Django 4.0.1 on 2022-01-28 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0041_alter_personlization_color_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon_name', models.CharField(max_length=50, verbose_name='icon name')),
                ('Title', models.CharField(help_text='title to be used for this particular services', max_length=60, verbose_name='Title of services')),
                ('Description', models.CharField(max_length=100, verbose_name='Description of services rendered')),
                ('Portfolio', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info')),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Servicess',
            },
        ),
    ]
