# Generated by Django 4.0.1 on 2022-01-28 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0042_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='Portfolio_name',
            field=models.CharField(default='MY PORTFOLIO CONFIG', max_length=50, null=True, verbose_name='portfolio_name/id'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Description',
            field=models.CharField(help_text='Description of this service', max_length=100, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='services',
            name='Icon_name',
            field=models.CharField(help_text='icon to be used for describing this service', max_length=50, verbose_name='icon name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info'),
        ),
    ]
