# Generated by Django 4.0.1 on 2022-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0043_alter_portfolio_portfolio_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Description',
            field=models.TextField(help_text='Description of this service', verbose_name='Description of services'),
        ),
    ]
