# Generated by Django 4.0.1 on 2022-01-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0046_personlization_service_background_picture_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlization',
            name='Service_background_picture_switch',
            field=models.BooleanField(default=True, null=True, verbose_name='ON or OFF picture on the service page'),
        ),
    ]
