# Generated by Django 4.0.1 on 2022-01-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0047_alter_personlization_service_background_picture_switch'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlization',
            name='Experience_background_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='Background picture for service experience page'),
        ),
        migrations.AddField(
            model_name='personlization',
            name='Experience_background_picture_switch',
            field=models.BooleanField(default=True, null=True, verbose_name='ON or OFF picture on the experiences page'),
        ),
    ]
