# Generated by Django 4.0.1 on 2022-02-02 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0049_alter_personlization_animation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=70, verbose_name='The Title of Post/Job')),
                ('Description', models.TextField(verbose_name='Description of Job done')),
                ('Start_date', models.DateField(verbose_name='Date Job Started')),
                ('End_date', models.DateField(verbose_name='Date Job Ended')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_story', models.TextField(verbose_name='User Experience Story')),
                ('Works', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.work', verbose_name='User work')),
            ],
            options={
                'verbose_name': 'Experience',
                'verbose_name_plural': 'Experiences',
            },
        ),
    ]
