# Generated by Django 4.0.1 on 2022-02-02 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0050_work_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Works',
        ),
        migrations.AddField(
            model_name='experience',
            name='Portfolio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info'),
        ),
        migrations.AddField(
            model_name='work',
            name='Experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.experience', verbose_name='User Experience'),
        ),
    ]
