# Generated by Django 4.0.1 on 2022-02-02 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0051_remove_experience_works_experience_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='Portfolio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info'),
        ),
    ]
