# Generated by Django 4.0.1 on 2022-02-02 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0053_alter_experience_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='Portfolio',
        ),
    ]
