# Generated by Django 4.0.1 on 2022-02-11 23:34

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0055_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioExhibit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20, verbose_name='Title of Work')),
                ('Short_Description', models.TextField(verbose_name='Work Short Description')),
                ('Date', models.DateField(verbose_name='Date of project')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_mail', models.EmailField(max_length=254, verbose_name='Contact EMail')),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(default='Enter phone number', help_text='Phone number to display on home page', max_length=128, region=None, verbose_name='Phone Number')),
                ('Website', models.URLField(verbose_name='Website Link')),
                ('Address', models.TextField(verbose_name='Address of Contact')),
                ('Portfolio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio', verbose_name='User_info')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
