# Generated by Django 4.0.1 on 2022-02-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0057_alter_contact_address_alter_contact_e_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlization',
            name='Contact_background_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='contact page bg'),
        ),
        migrations.AddField(
            model_name='personlization',
            name='Contact_background_picture_switch',
            field=models.BooleanField(default=True, null=True, verbose_name='contact page bg switch'),
        ),
    ]
