# Generated by Django 4.0.1 on 2022-02-14 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0058_personlization_contact_background_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personlization',
            name='Contact_background_picture_switch',
            field=models.BooleanField(default=False, null=True, verbose_name='contact page bg switch'),
        ),
        migrations.AlterField(
            model_name='personlization',
            name='Experience_background_picture_switch',
            field=models.BooleanField(default=False, null=True, verbose_name='experience page bg switch'),
        ),
        migrations.AlterField(
            model_name='personlization',
            name='Service_background_picture_switch',
            field=models.BooleanField(default=False, null=True, verbose_name='service page bg switch'),
        ),
    ]
