# Generated by Django 4.0.1 on 2022-02-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0059_alter_personlization_contact_background_picture_switch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personlization',
            name='blog_background_picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name='blog page bg'),
        ),
        migrations.AddField(
            model_name='personlization',
            name='blog_background_picture_switch',
            field=models.BooleanField(default=False, null=True, verbose_name='blog page bg switch'),
        ),
        migrations.AddField(
            model_name='personlization',
            name='blog_post_background_picture',
            field=models.ImageField(null=True, upload_to=None, verbose_name='blog post page bg'),
        ),
        migrations.AddField(
            model_name='personlization',
            name='blog_post_background_picture_switch',
            field=models.BooleanField(default=False, null=True, verbose_name='blog post page bg switch'),
        ),
    ]
